"""add language_preference to waitlist

Revision ID: 94786df877a2
Revises: 61963fed8cd7
Create Date: 2026-01-30 09:42:29.058289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94786df877a2'
down_revision: Union[str, None] = '61963fed8cd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('waitlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language_preference', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waitlist', schema=None) as batch_op:
        batch_op.drop_column('language_preference')

    # ### end Alembic commands ###
